### ISSUE TITLE
Cambios entre salas de un mismo mapa (fadeout y renderizado)

### ISSUE THREAD

**Issue by ClaudiaZarzuela** [UCM-FDI-DISIA/Fae-Studios#268]
Solo se debería renderizar la sala en la que se encuentra Ott. Debería poder cambiar entre salas al entrar a un trigger. Al pasar por el, se pondrá una animación fade-out, se cargará el mapa y se pondrá la animación fade-in. Los límites de la cámara deberán ser los de sala

**Comment by DavidRainder** [comment]
Esta tarea ha generado otra -> #420 
Se ha cerrado con el siguiente problema: las habitaciones son demasiado pequeñas para el ancho de la cámara, habría que reajustarlo
