### ISSUE TITLE
Implementar flote al cambiar de elemento en el mundo de agua

### ISSUE THREAD

**Issue by ClaudiaZarzuela** [UCM-FDI-DISIA/Fae-Studios#308]

**Comment by efeliua** [comment]
-material de agua que hace que cuando un personaje de agua colisiona se mueve normal con salto menos, con elemento distinto a agua asciende hasta que flota en el limite

**Comment by efeliua** [comment]
-lectura de objetos de agua añadidos en los mapas en tiled (mapComponent)

**Comment by efeliua** [comment]
-reajuste colisiones agua-jugador
-zona de salto añadida (ya no desde zona de flote en la superficie)
-bug arreglado atraviese lento de paredes al flotar + bugs producidos al tocar con el techo
