### ISSUE TITLE
Input de Mando

### ISSUE THREAD

**Issue by DavidRainder** [UCM-FDI-DISIA/Fae-Studios#32]

**Comment by DavidRainder** [comment]
He investigado acerca de cómo meter el input de mando y probado a usar todos los botones que tiene haciendo un programa bastante estúpido, pero que funciona increíble :)

**Comment by pablosm196** [comment]
Esta tarea tarea la empezó David (buscar el mapeo de los mandos y hacer que sdl reconozca el mando) y la he continuado yo, haciendo que funcionen los controles del mando y dando distintos feedbacks al jugador con la vibración y las luces.

**Comment by pablosm196** [comment]
d38d0e5
